### ISSUE TITLE
[활동페이지] 이미지 클릭이벤트=>모달 이미지 연동 && 애니메이션 변경

### ISSUE THREAD

**Issue by CWCTBOY** [Network-Leader/Homepage-FE#16]

**Comment by CWCTBOY** [comment]
~/De/_/N/Homepage-FE    feat-activity !36 )) git push origin feat-activity
>>> remote: Permission to Network-Leader/Homepage-FE.git denied to CWCTBOY.
>>> fatal: unable to access 'https://github.com/Network-Leader/Homepage-FE.git/': The requested URL
>>> returned error: 403
위 에러때문에 푸쉬 못하고 있는중..ㅠ

**Comment by seheon99** [comment]
권한에 문제가 있었어요 🥲 이제 푸시 될거에요
