### ISSUE TITLE
[메인페이지] Layout 구성

### ISSUE THREAD

**Issue by rlarlduf20** [Network-Leader/Homepage-FE#21]
## 이런 기능을 구현할거에요
Header와 Footer로 전체 Layout 구성

##회의시간에 아이디어로 나왔던 이런 기능을 구현할거에요
- [ ] Header에 Navbar
- [ ] materal ui 사용

## 이걸 구현하기 위해서는 이러한 내용을 알아야해요
- [공부 주제 1]https://mui.com
- Next.js `_document.tsx`
  - _document를 작성할 때는 Document 클래스를 상속받는 클래스형 컴포넌트로만 작성해야만 하며, 렌더함수는 꼭 `<Html>`, `<Head>`, `<Main>`, `<NextScript>` 요소를 리턴해줘야 한다.
  - _document에서 사용하는 `<Head>`태그는 next/head가 아닌 next/document모듈에서 불러와야하고, _document의 `<Head>`태그에는 모든 문서에 공통적으로 적용될 내용(ex) charset,뷰포트 메타태그 등) 이 들어가야 한다.
  - _document는 서버사이드에 관여하는 로직 또는 static한 로직을 추가하는데 사용한다.
  - 서버에서 받아온 html, css와 클라이언트가 렌더링한 html,css가 다르면 next에서 waring을 띄운다. 그래서 서버단에서 mui를 지원함으로 서버와 클라이언트간 간극을 맞추기 위해 설정을 해줘야한다.

## 이 기능은 이런 목적에서 시작했어요 / 어떤 불편함이 있어서 추가하게 되었어요
모든 페이지에 들어가는 공통의 Layout 작성

**Comment by seheon99** [comment]
`src/pages/_document.tsx` 에 작성된 주석을 여기로 옮겼어요
