### ISSUE TITLE
[회원가입] User position 관련 질문

### ISSUE THREAD

**Issue by happyjamy** [Network-Leader/Homepage-FE#71]
## 발견 당시 상황과 목적을 간단히 설명해주세요

swagger에 구현 된 스키마들 중 User 스키마에 position 값이 설정되어 있는데,
CreateUser, UpdateUser 둘 다 position 값을 받지 않네요.
position 값은 어디서 받는건지 아직 안 정해진건지 답변 부탁드립니다~!

**Comment by seheon99** [comment]
아직은 회원가입에서 포지션을 받지 않고 유저 정보 수정에서 작성할 것 같아요
`CreateUser` 에는 없고 `UpdateUser` 에서 `position` 을 받게 될 것 같아요
