### ISSUE TITLE
[TuiCalendar.tsx] DevOps팀 : npm build 오류

### ISSUE THREAD

**Issue by newdeal123** [Network-Leader/Homepage-FE#91]
## 발견 당시 상황과 목적을 간단히 설명해주세요
프론트엔드 서버에서 빌드가 안되는 오류가 발생해버렸습니다 

## 버그를 재현할 수 있는 방법을 알려주세요

1. 프론트엔드 서버 접속 후
2.  npm run build를 하면?
3.  짜잔

## Screenshots
<img width="946" alt="image" src="https://user-images.githubusercontent.com/31841502/178095348-0c52e9a9-1759-433f-bfe0-3423f7882677.png">

## System Info

- OS: [i-0a133670c64f90d11(NL_AWS_FE), Amazon linux2 t3.medium]

**Comment by seheon99** [comment]
- #73

**Comment by newdeal123** [comment]
해결되었읍니다~

`npm install --legacy-peer-deps`
